### PR TITLE
more config file extensions

### PR DESCRIPTION
**Pull request by asinbow**
Support more extensions of mirrord config files according to the [doc](https://mirrord.dev/docs/overview/quick-start/#intellij-plugin).

### CODE REVIEW

**Comment by aviramha** [comment]
Hey @asinbow ! Thanks for this contribution.
We'd need a few more changes for other extensions to work, more specifically see the `isTargetSet` function which parses the configuration from the extension.
Having said that, we plan on changing the extension to use the cli to parse configurations, then we won't have any format specific (yaml,json,toml) in our extensions.
I think we'll put this on hold until we do the refactor, but if you'd like to support the `isTargetSet` for other formats we will accept it (just letting you know it might be in vain)

**Comment by asinbow** [comment]
Thanks @aviramha! Looking forward to the future change.

FYI the reason why I need support for YAML is I need to put some comments on configurable env variables.
```yaml
feature:
env:
  override:
    # possible values: a, b, c
    MY_ENV: a
```

It would be helpful for my team members.

**Comment by aviramha** [comment]
Hey, wanted to give you an update that we prioritized necessary work to get this merged! Sorry about the delay!

**Review by aviramha — APPROVED** [review]

**Comment by aviramha** [comment]
Sorry for taking this long!

**Pull request merged**
